### ISSUE TITLE
Removal of excess directories in build takes out a couple of extras in enterprise, one of which definitely shouldn't

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba#191]
```bash
doodba INFO: Removing subdirectory /opt/odoo/custom/src/enterprise/documents_mrp
doodba INFO: Removing subdirectory /opt/odoo/custom/src/enterprise/iot_drivers
```

**Comment by Yajo** [comment]
Can you paste your `addons.yaml`?

**Comment by gdgellatly** [comment]
Well this is the relevant line

```
enterprise:
    - '*'
```

**Comment by Yajo** [comment]
Do you use multiple docs or env-var-based filters in the `addons.yaml`?

**Comment by gdgellatly** [comment]
@yajo - I think the common factor is both of those *modules* do not have manifest files. One is just translations and the other is drivers.

**Comment by Yajo** [comment]
Yep, that's the problem. Nothing to do there then, since the only things supported there are addons. Just add the build arg `CLEAN=false` to your scaffolding to disable that cleanup, which is enabled by default:

https://github.com/Tecnativa/doodba/blob/d79f5913976bfc2485339ea733f17a73ff6e7ef9/12.0.Dockerfile#L136

**Comment by gdgellatly** [comment]
i disagree. I think using an * should mean everything, . It seems pretty c;lear that the editor feels these folders are part of enterprise, so I don't see why doodba should delete them if a * is used in addons.yaml.

**Comment by Yajo** [comment]
Well, actually a `*` means *all addons in this directory*, not *all files in this directory*.

If you still have `CLEAN=true`, Doodba understands you actually want to keep a small build, removing _everything that is not an addon_.

Possibly the bug is actually in enterprise code, where the drivers folder should exist inside the `iot` addon itself, or [the code inside should be used somewhere, which is not the case](https://github.com/odoo/enterprise/search?q=iot_drivers&type=Code). Open an issue there and let's see what they say.

About the `documents_mrp` folder, I cannot find it anywhere, so I cannot give you an advice.

If you come to some different design that you find better, we're open to reviewing your PR. Thanks!

**Comment by gdgellatly** [comment]
@yajo you cannot see it because you haven't got a private mirror of enterprise that hasn't been updated for a couple of months (oops).

However the iot_drivers code is absolutely used inside Odoo, it is referenced in the route /iot/get_drivers which essentially globs the addons path for drivers folders. But I don't see why the drivers can't be inside the iot module anyway. I'll ask.
