### ISSUE TITLE
odoo oca repo

### ISSUE THREAD

**Issue by mokerosan** [Tecnativa/doodba#226]
First of all, congratulations for this excellent project. I have a problem, I do not know why they reasoned when I installed the database in Spanish, some parts of the page appear in English and others in Spanish, this did not happen to me when I used the repo de odoo S.A. there is some possibility of translating it or using the odoo repo S.A.

**Comment by pedrobaeza** [comment]
@mokerosan the problem you are facing is because you are using it locallly with devel.yaml, and that environment provides by default the parameter to the server `--dev=all`, which is a special Odoo mode for loading views on the fly (with other development facilities). The trade-off of this is that translations are not performed. Disable that parameter on the yaml file or use another environment for having them translated. Note that on demo and prod environments this is not activated.
