### ISSUE TITLE
Not an issue, just not sure where else to ask questions

### ISSUE THREAD

**Issue by theangryangel** [Tecnativa/doodba#284]
Not so much an issue, but I didn't know where else to ask. If there's a more appropriate venue, let me know.

I'll be upfront I'm currently using dockery-odoo and I'm investigating doodba as an alternative as there seems to be more community around doodba. 

There are many things I'm finding attractive about doodba, however there are 2 things I think I'm confused by. Please forgive me if I'm missing something obvious/being daft.

First is enterprise;

I can see that there are checks for a special repo called "enterprise", but I'm not seeing how it's supposed to auto-link into the addons directory? Or are we supposed to add all the enterprise modules to addons.yml?

Second is image size;

I've just built an image locally using `docker-compose -f prod.yml build`, and `docker image ls` is showing me an image size of about 2.69GB. This is without enterprise, without anything custom, etc.

This seems quite large? Am I doing something wrong? Or is that just the way it is? Should I be looking to removing stuff from the container for prod? For context I'm building prod containers at about 892.66MB using dockery-odoo currently - the main reason why size is a concern is that currently we're running gitlab on-prem with S3 backing our container registry, and a few of our customers are on-prem, and throwing around multi-GB images can be painful.

**Comment by Yajo** [comment]
Hi there and welcome to doodba, I hope you like it! :blush: 



> there seems to be more community around doodba.

It feels so cool to hear that, would you be so kind to indicate some resources on that? Just curiosity...

> Not so much an issue, but I didn't know where else to ask. If there's a more appropriate venue, let me know.

I guess issues is a good place, yes. :wink: 

I'd love to add an official Matrix channel in the future, but don't take that as an official statement.

Well, let's get into business.

> I can see that there are checks for a special repo called "enterprise", but I'm not seeing how it's supposed to auto-link into the addons directory?

I guess that's a recent addition (#264) that wasn't properly documented. All that was done regarding enterprise is that it was added as a special category in [the `addons` script](https://github.com/Tecnativa/doodba/blob/c7058f6d6f9ac7f51adeb74fe47bc80bc2a33680/bin/addons).

The reasoning behind this change is that integrating enterprise addons into your downstream CI pipelines is almost impossible. For other repos it's easier because you can send patches, but in enterprise they're not gonna accept any patch for tests in integration environments. All @odoo cares about is that their own CI is green.

I guess this was a quick patch that would have been better by allowing to exclude/include a full repo (be it enterprise or any other).

> are we supposed to add all the enterprise modules to addons.yml?

Apart from what I said above, enterprise is treated like any other addon, so yes, you have to specify which addons to include (which can be all using `enterprise: ['*']`, just like other repos).



> This seems quite large? Am I doing something wrong? Or is that just the way it is?

Well now about this... It's a problem indeed, but it's somehow the way it is. However it depends also on the version you're building.

- Versions 7-10: https://github.com/Tecnativa/doodba/blob/c7058f6d6f9ac7f51adeb74fe47bc80bc2a33680/8.0.Dockerfile#L1
- Versions 11-12: https://github.com/Tecnativa/doodba/blob/c7058f6d6f9ac7f51adeb74fe47bc80bc2a33680/11.0.Dockerfile#L1
- Version 13: https://github.com/Tecnativa/doodba/blob/c7058f6d6f9ac7f51adeb74fe47bc80bc2a33680/13.0.Dockerfile#L1

As you see, we started using just Debian, installing the python version shipped by them. At some point we realized we could use lang-specific images which were also based on Debian, but those images are quite bloated (pro: less build deps to care about, con: more space). At the end I switched in v13 to the lang-specific-but-slim version, which seems to be the best balance.

So, it's expected that images in v11-12 are biggest. And we cannot change that or we'd break many deployments out there, that's why we do these kind of changes when changing the odoo version; if you want to propose something as different as changing a base, we can discuss it for v14.

When thinking on this subject, don't forget:

1. Odoo code is huge.
1. Odoo can use things like Less (node) and Sass (ruby). Given v12+ doesn't make actual use of that out of the box (although support is included out of the box), I would eagerly consider removing these stacks for v14 if possible. That should flatten the size quite a bit.
1. We need to include tools for dev, qa and sysadmin work in the base image.

And before you ask, Alpine doesn't work for Odoo: https://github.com/Tecnativa/doodba/issues/16

However, you know Docker uses layers, so this means that once you push an image based on (say) `tecnativa/doodba:13.0-onbuild`, all those layers are not going to be pushed again. The same when downloaded. So, the only diff you should care about is the one built in the `ONBUILD` stage (which can be huge too, even if we do some cleanups as we do currently (i.e. we remove all `.git` folders and unwanted addons)).

Also you should be able to leverage tools like Skopeo to push images among registries without having to download them.

Recently we started doing weekly builds of the base images automatically. We did that to ensure we have latest upstream security patches, but if that causes some trouble, I'd be glad to improve that with the community.

Finally, it's a decision of this project to inflate the base image as much as needed to have all needed tools built-in. The reasons of doing this is what I just explained: you just download once a big blob, and everything just works out of the box. Other layers based on this blob won't ask you to download it again, and hard drive/network are some of the cheapest resources in the IT world, so this was the direction we took and TBH after some years we don't regret it. It doesn't mean it can't be improved, of course, but we're probably going to be hesitant to sacrifice UX just to save some MB.


> currently we're running gitlab on-prem with S3 backing our container registry, and a few of our customers are on-prem

That's our exact situation too. It works like a charm. Just make sure to clean up your registry every now and then. See https://docs.gitlab.com/ee/administration/packages/container_registry.html#container-registry-garbage-collection

Let me close this as I think I responded all your questions, but feel free to continue/reopen/open another/etc.

**Comment by theangryangel** [comment]
Just wanted to say thank you for taking the time, much appreciated :+1: Looking forward to experimenting more with doodba
