### ISSUE TITLE
SSH agent forwarding

### ISSUE THREAD

**Issue by hbrunn** [Tecnativa/doodba#292]
I'm currently evaluating doodba as an alternative for buildout, nice work from what I saw so far!

My question is about how you handle keys. Do I understand correctly you check in deployment keys?

I'm currently doing this

```diff
diff --git a/setup-devel.yaml b/setup-devel.yaml
index 0ff285c..43cebd0 100644
--- a/setup-devel.yaml
+++ b/setup-devel.yaml
@@ -26,12 +26,14 @@ services:
             - public
         volumes:
             - ./odoo/custom/src:/opt/odoo/custom/src:rw,z
+            - ${SSH_AUTH_SOCK:-./odoo/custom/ssh}:/ssh-agent
         environment:
             DEPTH_DEFAULT: 100
             # XXX Export these variables before running setup to own the files
             UID: "${UID:-1000}"
             GID: "${GID:-1000}"
             UMASK: "$UMASK"
+            SSH_AUTH_SOCK: "/ssh-agent"
         user: root
         entrypoint: autoaggregate
```

to have docker use whatever keys were added to my ssh agent, and plan to do the same for deployments, so that there's never actually a key on the customer's/hoster's server.

Did you consider this and there's reasons not to do it like that?

**Comment by Yajo** [comment]
What would happen if that env variable didn't exist? The mounting of the ssh local folder would work? :thinking: That doesn't seem like valid...

If you can provide logs on how this would work, I would be more pleasant to merge it, as I consider it a good improvement indeed.

> Did you consider this and there's reasons not to do it like that?

I didn't consider this because it hasn't been a priority. `setup-devel` is for development environments, where the developer *needs* the source code. For me, giving access to the source code of a doodba deployment automatically means you give it access to any code it needs to work. Using deployment keys with read-only access make sure that you can always rotate them if a dev goes away. The same for deploy tokens.

For CI/staging/production, I'd need to have deployment keys on the servers if I wanted to use this, but it turns out `test.yaml` and `prod.yaml` are (and IMHO must be) completely declarative. I didn't want them to depend on the environment they run (different from devel of course). They are intended to produce a full docker image with all code inside, so I'm not sure this would fit all the supported environments. If you don't provide this to test and prod, the wouldn't be able to build, right?

**Comment by Yajo** [comment]
Closing in favor of https://github.com/Tecnativa/doodba-copier-template/issues/15.
