### ISSUE TITLE
Include latest version of openupgradelib

### ISSUE THREAD

**Issue by pedrobaeza** [Tecnativa/doodba#318]
It doesn't make sense to include an outdated pypi version. The functional one is always:
```
git+https://github.com/OCA/openupgradelib.git@master
```
Having to put that latest version in pip.txt is a nonsense, as if not put, you get weird errors that you have to trace until finding that is an outdated version.

**Comment by Yajo** [comment]
We don't ship that library on doodba, and that's on purpose.

If we did, then to update it, you'd need to:

1. Rebuild doodba base images. This includes running the whole CI suite.
1. Rebuild your sub-images.

This doesn't make much sense because it's obvious that, you expect the very latest commit. Actually, when developing a migration, often you need a different branch that includes some patches to the library. Some other people could prefer to pin a commit, and that's not something we should forbid here.

So, the solution we took at #214 was to remove `openupgradelib`, so we can skip step 1 and make migrations more agile. This comes at the cost of having that line on your scaffolding, but the benefits are worth it.

If you happen to find the pypi version of `openupgradelib` on your image, the reason must be elsewhere.
